### ISSUE TITLE
Écrire un script pour parser les fichiers de données

### ISSUE THREAD

**Issue by YuanxiangFranck** [YuanxiangFranck/PIE_ISAE_Essais_Vol#2]

**Comment by FlorentF9** [comment]
- [x] NaN !!
- [x] Parse signal names (e.g. dictionary with label/ID correspondance)
- [x] Parse signal units

**Comment by FlorentF9** [comment]
- [x] Parser tous les signaux du fichier de données, sans utiliser signals_to_monitor.txt !

**Comment by FlorentF9** [comment]
Tu devrais obtenir ça en plottant les signaux BLEED_OUT_TEMP_AMSCX_CHX
![bleed_out_temp](https://cloud.githubusercontent.com/assets/22910528/20039679/2b7189d2-a448-11e6-8b61-e3929a0d9192.png)

**Comment by YuanxiangFranck** [comment]
en fait j'avais mal comprit le fichier de donnée, la ligne 9 (PTIME    21209011@CL1_CH1_0128_0 21209013@CL1_CH1_0128_0 21209015@CL1_CH1_0128_0 21209017@CL1_CH1_0128_0 )
représente pas les noms des signaux mais quelque chose d'autre (port d’acquisition? )

**Comment by FlorentF9** [comment]
- [ ] axe des temps démarrant à 0 (relatif) pour le plot

**Comment by YuanxiangFranck** [comment]
le pas de temps des données est de 1, donc il est inutile de calculer le temps relatif sur une nouvelle colonne.
Par contre j'ai quand même ajouté une colonne «rTime» qui donne le temps relatif pour que le tout reste cohérent.
@fireparis c'est un truc qu'il va falloir noter dans la documentation plus tard....

**Comment by YuanxiangFranck** [comment]
https://github.com/YuanxiangFranck/PIE_ISAE_Essais_Vol/blob/master/dataProcessing/parser.py#L49

**Comment by YuanxiangFranck** [comment]
fini
