### ISSUE TITLE
Manage constant target signals with names like '41psig'

### ISSUE THREAD

**Issue by FlorentF9** [YuanxiangFranck/PIE_ISAE_Essais_Vol#22]
Certaines target (correspondant par ex à des valves pneumatiques) n'ont pas de target mais une valeur constante. Le nom de la target associée est une constante + une unité (ex : '41psig').

Il faut rentrer cette valeur constante dans le DataFrame des données du vol !

cf algorithms/flight_analysis_fun.py load_flights

**Comment by YuanxiangFranck** [comment]
https://github.com/YuanxiangFranck/PIE_ISAE_Essais_Vol/blob/master/dataProcessing/parser.py#L57

Je traite maintenant toutes les target du type : ***psig

Reste à voire s'il on risque de rencontrer d'autres types de formats
