### ISSUE TITLE
Implement flight segmentation

### ISSUE THREAD

**Issue by FlorentF9** [YuanxiangFranck/PIE_ISAE_Essais_Vol#5]
* input : relevant signals
* output : start/end dates of flight segments

**Comment by FirePingui** [comment]
- [x] TO DO : input : dataframe, output : dictionnary with names of segments as keys and lists of tuples (start,end) as values (the case where a flight segment is not concomitant (eg. on the ground) must be taken into account )
- [x] TO DO : implémenter des fonctions affichant la segmentation sur des signaux intéressants (vérification visuelle de la validité de la segmentation)
- [ ] TO DO : définir des intervalles de temps de transition autour des coupures ?

**Comment by FlorentF9** [comment]
- [x] Implémenter un filtrage (par ex. moyenne glissante de 60s) sur Vza et éventuellement d'autres signaux pour éviter les changements de phase de vol  intempestifs

`data_filt = data.rolling(center = False, window = windowSize).mean()`

**Comment by QuentinJcb** [comment]
- [x] implémenter la nouvelle segmentation (cf sharepoint)

**Comment by QuentinJcb** [comment]
- [ ] TO DO : modifier le filtrage du  signal relatif à la CAS pour landing et take_off -> ne donne pas de bons résultats pour le moment

**Comment by FlorentF9** [comment]
- [ ] Segmentation IP/HP/APU

**Comment by YuanxiangFranck** [comment]
Pour la nouvelle visualisation il y a un problème:
Lorsqu'il y a des recouvrements je ne peux pas avoir une barre unique....
Des idées?

**Comment by YuanxiangFranck** [comment]
Nouvelle visu qui permet pour gérer les conflits 
![image](https://cloud.githubusercontent.com/assets/14313188/21912595/47519e26-d927-11e6-9b6c-7892982bc6d1.png)
