### ISSUE TITLE
Implement new data class and feature extraction

### ISSUE THREAD

**Issue by FlorentF9** [YuanxiangFranck/PIE_ISAE_Essais_Vol#7]
Création d'une nouvelle classe pour structurer les données avant d'y appliquer les algorithmes de détection : 
* stockage d'un signal ou plusieurs signaux dans une matrice de données
* possibilité de stockage de timeseries complètes ou sous forme de subsequences (sliding window)
* méthodes d'extraction de features
* gestion des signaux continus ou binaires

Exemple de features :
1. Descripteurs statistiques des signaux : 
- [x] min, max, amplitude, moyenne, variance
- [x] fréquence (Fourier (FFT), décomposition en cosinus, ondelettes...)
- [x] nombre de transitions 0/1 pour signaux binaires
- [x] nombre de pas de temps dépassant un certain seuil (utile pour calculer le temps passé hors régulation)
- [x] nombre de passages de la moyenne
- [x] nombre de passages au-dessus d'un seuil (afin de détecter d'éventuelles oscillations)

2. Autres descripteurs : 
- [ ] Pour un sous-segment de vol : ajouter une feature indiquant dans quelle phase de vol il se trouve actuellement (sous forme de variables dummy par exemple); prendre en compte aussi les histoires de ports IP/HP
- [ ] Pour un vol entier : ajouter une feature indiquant par exemple le temps passé dans chaque phase de vol (idem)
- [ ] Développer des features liées aux phases de vol pour caractériser un vol entier (features génériques par phase, ou spécifiques à certaines phases ?)

A COMPLÉTER !

**Comment by YuanxiangFranck** [comment]
je suis pas sur de comprendre le choix d'avoir en entrée de SignalData une list de signaux, pourquoi ne pas donner une dataframe en entrée?
https://github.com/YuanxiangFranck/PIE_ISAE_Essais_Vol/blob/master/algorithms/SignalData.py#L20

Par exemple dans https://github.com/YuanxiangFranck/PIE_ISAE_Essais_Vol/blob/master/algorithms/n_flights.py#L34

On pourrait faire ca:
```python
##  avant: 
signals = [flight_data[sig[0]].iloc[:,0] for sig in signal_names[:1000]]
# Extract features for each flight
sigData = SignalData(signals)

## Autre idée: si SignalData prend une Dataframe en entrée
signals = filght_data.iloc[:, :1000]
sigData = SignalData(signals)
```

**Comment by YuanxiangFranck** [comment]
au fait pour manipuler des sliding window il existe deja des outils dans pandas (merci stackoverflow )
http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.rolling_mean.html
http://pandas.pydata.org/pandas-docs/stable/computation.html#window-functions

**Comment by FlorentF9** [comment]
Oui il y a sûrement une façon plus efficace de le faire... Mais bon c'est pas la priorité, d'abord pour le 4 janvier il faut qu'on puisse leur montrer des algos/visualisations qui mettent en évidence des anomalies, le reste on s'en occupera plus tard pendant l'intégration !
