### ISSUE TITLE
Display flight phases on plot

### ISSUE THREAD

**Issue by FlorentF9** [YuanxiangFranck/PIE_ISAE_Essais_Vol#8]
- [x] Affichage des différentes phases de vol sur les plots de signaux (avec par ex. des traits en pointillés pour délimiter chaque phase)
- [x] Affichage du nom de la phase de vol sur le plot ? (sauf si ça ne rentre pas sur le graphique, par ex. si la phase est trop courte)

**Comment by YuanxiangFranck** [comment]
fini
